### ISSUE TITLE
very good design ,but can give us more detail document to explain?

### ISSUE THREAD

**Issue by zppro** [kilgaloon/leprechaun#99]
@kilgaloon 
has any detail document for quick start ?,i think why so few person stars is that the leprechaun is not friendly to users to teach them how to build schedule system  with it.
your readme is far from  enough.
I expect see the document as soon as possible.because i like the leprechaun.

**Comment by kilgaloon** [comment]
Hey @zppro 

Thanks for kind comments, can you please tell me on what documentation you are referring to, is it like something how to contribute? or how to use leprechaun in general?

**Comment by zppro** [comment]
Hey @kilgaloon 
I think the most important thing is to introduce in general what leprechaun is, what parts it is composed of, and what responsibilities each part bears. 
The officially defined recipe type (schedule, hook, cron) should be used in any scenario. How to quickly connect with existing systems. I took a look at the overall code structure of leprechaun. It should be the biggest design ambition I have seen in the open source library for the timed task class. But I think there is still a lot to be done to reach your ultimate goal. But as users we only have a vague concept.
 I hope that you can express some of your design ideas. So we can understand that there is a client, api? Are we using cli or http when we manage recipes? There are also recipe files and so on for not using the associated database. I have so much, or because I hope to integrate leprechaun into existing systems.
Thanks a lot

**Comment by zppro** [comment]
maybe，[nsq](https://nsq.io/overview/design.html) is good example

**Comment by kilgaloon** [comment]
@zppro i had idea about something similar document that can describe closely idea behind Leprechaun and some of the design decision i put in it. Currently i lack free time to create something like that, i will try my best. I have more ideas for Leprechaun regarding new functionalities and code changes and updates but like i said, currently i lack free time to do that.

Thanks for you contributions an ideas.

**Comment by kilgaloon** [comment]
I worked a bit on this and here you can find some basic explanation of some general things: [IDEA](https://github.com/kilgaloon/leprechaun/blob/development/IDEA.md)
